name: "Default Branch"

on: [push]

jobs:
  which-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if running on default branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/${{ github.event.repository.default_branch }}" ]; then
            echo "Running on the default branch."
          else
            echo "Not running on the default branch."
          fi