name: "Default Branch"

on: [push]

jobs:
  which-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if running on default branch
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "On the default branch"
      - if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "Not on the default branch"

